version: 2

sources:
  - name: raw
    schema: public
    tables:
      - name: orders
      - name: order_items
      - name: customers
      - name: sessions
      - name: campaigns
      - name: marketing_spend
      - name: marketing_spend_by_campaign
      - name: marketing_spend_unassigned
      - name: products
