name: Build Analytics Models (Aiven PostgreSQL)

on:
  push:
    branches: [main]
    paths:
      - "schema.sql"
      - "Ecommerce_data/**.psql"
      - ".github/workflows/project.yaml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      # 1) Base DDL for raw tables (public.*)
      - name: Apply schema.sql (raw tables in public)
        if: hashFiles('schema.sql') != ''
        env:
          PGHOST: analytics-analytics-6e35.d.aivencloud.com
          PGPORT: "27742"
          PGDATABASE: defaultdb
          PGUSER: ci_migrator
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
          PGSSLMODE: require
        run: |
          echo "Running schema.sql"
          psql -v ON_ERROR_STOP=1 -f schema.sql

      # 2) Data loads that populate public.*
      - name: Run Ecommerce_data loaders
        env:
          PGHOST: analytics-analytics-6e35.d.aivencloud.com
          PGPORT: "27742"
          PGDATABASE: defaultdb
          PGUSER: ci_migrator
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
          PGSSLMODE: require
        run: |
          set -euo pipefail
          shopt -s nullglob
          for f in Ecommerce_data/*.psql; do
            echo "=== Executing $f ==="
            psql -v ON_ERROR_STOP=1 -f "$f"
          done
