name: DBT model

on:
  push:
    branches: [main]
    paths:
      - "Ecommerce_data/**/*.sql"
      - "Ecommerce_data/**/*.psql"
      - ".github/workflows/project.yml"
      - "dbt_project.yml"
      - "profiles/profiles.yml"
  workflow_dispatch: {}

jobs:
  dbt:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}  # used in profiles.yml via {{ env_var('DB_PASSWORD') }}
      DBT_PROFILES_DIR: profiles

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # handy for future state/selection

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt-postgres
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres

      - name: dbt debug (verify connection & profile)
        run: dbt debug --no-use-colors

      # Optional: run seeds if you add CSVs under ./seeds
      - name: dbt seed (optional)
        run: |
          if [ -d "seeds" ] && [ -n "$(find seeds -type f -name '*.csv' -print -quit)" ]; then
            dbt seed --no-use-colors
          else
            echo "No seeds to load."
          fi

      # 🔥 Build models (this is the step you were missing)
      - name: dbt build (models + tests)
        run: dbt build --no-use-colors

      # Helpful: list the models dbt saw (quick sanity check in logs)
      - name: dbt ls (show models)
        run: dbt ls --resource-type model

    
