name: DBT model

on:
  push:
    branches: [main]
    paths:
      - "Ecommerce_data/**/*.sql"
      - "Ecommerce_data/**/*.psql"
      - ".github/workflows/project.yml"
      - "dbt_project.yml"
      - "profiles/profiles.yml"
  workflow_dispatch: {}

jobs:
  dbt:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      # used by profiles/profiles.yml: password: "{{ env_var('DB_PASSWORD') }}"
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      # so we don't need to pass --profiles-dir each command
      DBT_PROFILES_DIR: profiles

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # helpful if you later use state/selection by diff

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt-postgres
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres

      - name: dbt debug (verify connection)
        run: dbt debug --no-use-colors

      # Optional: run seeds if you add CSVs under ./seeds
      - name: dbt seed (optional)
        run: |
          if [ -d "seeds" ] && [ -n "$(find seeds -type f -name '*.csv' -print -quit)" ]; then
            dbt seed --no-use-colors
          else
            echo "No seeds to load."
          fi
