name: DBT model

on:
  push:
    branches: [main]
    paths:
      - "Ecommerce_data_modeling/**/*.sql"
      - "Ecommerce_data_modeling/**/*.psql"
      - ".github/workflows/project.yml"
      - "dbt_project.yml"
      - "profiles/profiles.yml"
  workflow_dispatch: {}

jobs:
  dbt:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }} 
      DBT_PROFILES_DIR: profiles

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt-postgres
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres

      - name: dbt debug (verify connection & profile)
        run: dbt debug --no-use-colors

      # run seeds
      - name: dbt seed (optional)
        run: |
          if [ -d "seeds" ] && [ -n "$(find seeds -type f -name '*.csv' -print -quit)" ]; then
            dbt seed --no-use-colors
          else
            echo "No seeds to load."
          fi

      #Run DBT models and tests
      - name: dbt build (models + tests)
        run: dbt build --no-use-colors

      #list the models dbt saw (quick sanity check in logs)
      - name: dbt ls (show models)
        run: dbt ls --resource-type model

    
