name: Run New or Updated SQL (Aiven PostgreSQL)

on:
  push:
    branches: [main]
    paths:
      - "Ecommerce_data/**/*.sql"
      - "Ecommerce_data/**/*.psql"
      - ".github/workflows/project.yml"
      - "dbt_project.yml"
      - "profiles/profiles.yml"
  workflow_dispatch: {}

jobs:
  run-new-sql:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Execute only new or modified SQL files
        env:
          PGHOST: analytics-analytics-6e35.d.aivencloud.com
          PGPORT: "27742"
          PGDATABASE: defaultdb
          PGUSER: ci_migrator
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
          PGSSLMODE: require
        shell: bash
        run: |
          set -euo pipefail

          # Get only the new or modified files in this commit
          mapfile -t files < <(git diff --name-only origin/main...HEAD -- 'Ecommerce_data/**/*.sql' 'Ecommerce_data/**/*.psql' | grep -v '^$' || true)

          if [ ${#files[@]} -eq 0 ]; then
            echo "No new or updated SQL files found."
            exit 0
          fi

          echo "Running new or updated SQL files:"
          printf '  %s\n' "${files[@]}"

          for f in "${files[@]}"; do
            if [ -f "$f" ]; then
              echo "=== Executing $f ==="
              psql -v ON_ERROR_STOP=1 -1 -f "$f"
            fi
          done

      - name: Verify connection (optional sanity check)
        env:
          PGHOST: analytics-analytics-6e35.d.aivencloud.com
          PGPORT: "27742"
          PGDATABASE: defaultdb
          PGUSER: ci_migrator
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
          PGSSLMODE: require
        run: |
          psql -v ON_ERROR_STOP=1 -c "SELECT 'Workflow executed successfully' AS status, NOW() AS executed_at;"
