name: Run Ecommerce SQL (Aiven PostgreSQL)

on:
  push:
    branches: [main]
    paths:
      - "Ecommerce_data/**/*.sql"
      - "Ecommerce_data/**/*.psql"
      - ".github/workflows/project.yml"
  workflow_dispatch: {}

jobs:
  run-ecommerce-sql:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Execute changed SQL in Ecommerce_data/
        env:
          PGHOST: analytics-analytics-6e35.d.aivencloud.com
          PGPORT: "27742"
          PGDATABASE: defaultdb
          PGUSER: ci_migrator
          PGPASSWORD: Krishna@cloud09
          PGSSLMODE: require
        shell: bash
        run: |
          set -euo pipefail

          # Build a list of .sql/.psql files to run
          if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
            # only files changed in this push
            mapfile -t files < <(git diff --name-only HEAD~1 HEAD -- \
                                   'Ecommerce_data/**/*.sql' 'Ecommerce_data/**/*.psql' \
                                 | xargs -I{} bash -lc '[ -f "{}" ] && echo "{}"' \
                                 | sort -u)
          else
            # first run: all files in the folder
            mapfile -t files < <(find Ecommerce_data -type f \( -name '*.sql' -o -name '*.psql' \) | sort)
          fi

          if [ ${#files[@]} -eq 0 ]; then
            echo "No SQL changes in Ecommerce_data/."
            exit 0
          fi

          echo "Running these files:"
          printf '  %s\n' "${files[@]}"

          for f in "${files[@]}"; do
            echo "=== Executing $f ==="
            psql -v ON_ERROR_STOP=1 -f "$f"
          done

      - name: Smoke check
        env:
          PGHOST: analytics-analytics-6e35.d.aivencloud.com
          PGPORT: "27742"
          PGDATABASE: defaultdb
          PGUSER: ci_migrator
          PGPASSWORD: Krishna@cloud09
          PGSSLMODE: require
        run: |
          psql -v ON_ERROR_STOP=1 -c "SELECT now() AS ran_at;"
